/* ****************************
 * Tables
 * ****************************/
DROP TABLE IF EXISTS MONEY_SPRAYING;
CREATE TABLE MONEY_SPRAYING
(
    SPRAYING_ID     BIGINT            NOT NULL    AUTO_INCREMENT COMMENT '뿌리기 아이디', 
    ROOM_ID         VARCHAR(20)       NOT NULL    COMMENT '대화방 아이디', 
    TOTAL_COUNT     INT               NOT NULL    COMMENT '총 인원수', 
    TOTAL_AMOUNT    DECIMAL(18, 2)    NOT NULL    COMMENT '총 금액', 
    REMIT_AMOUNT	DECIMAL(18, 2)    NOT NULL    COMMENT '송금액(다른 사람이 받기 완료한 금액)',
    TOKEN           CHAR(3)           NOT NULL    COMMENT '토큰', 
    -- STATUS          CHAR(8)           NOT NULL    COMMENT '요청 상태', 
    USER_ID         BIGINT            NOT NULL    COMMENT '생성자 아이디', 
    CREATE_AT       TIMESTAMP         NOT NULL    COMMENT '생성 시각', 
    PRIMARY KEY (SPRAYING_ID)
);

--ALTER TABLE MONEY_SPRAYING COMMENT '뿌리기 요청';
ALTER TABLE MONEY_SPRAYING ALTER COLUMN CREATE_AT SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE MONEY_SPRAYING ALTER COLUMN REMIT_AMOUNT SET DEFAULT 0;

DROP TABLE IF EXISTS MONEY_SPRAYING_DETAIL;
CREATE TABLE MONEY_SPRAYING_DETAIL
(
    SPRAYING_DTL_ID  BIGINT            NOT NULL    AUTO_INCREMENT COMMENT '뿌리기 상세 아이디', 
    SPRAYING_ID      BIGINT            NOT NULL    COMMENT '뿌리기 요청 아이디', 
    AMOUNT           DECIMAL(18, 2)    NOT NULL    COMMENT '뿌리기 금액', 
    USER_ID          BIGINT            NULL        COMMENT '수신자 아이디', 
    CREATE_AT        TIMESTAMP         NULL        COMMENT '받은 시각', 
    PRIMARY KEY (SPRAYING_DTL_ID)
);

--ALTER TABLE MONEY_SPRAYING_DETAIL COMMENT '뿌리기 개별 내역';
ALTER TABLE MONEY_SPRAYING_DETAIL ALTER COLUMN CREATE_AT SET DEFAULT CURRENT_TIMESTAMP;